/*
AGENDA :
    Normalization
    codds Rules
    NoSQL : Mongodb

*/


// MongoDb
/* Mongo is NoSQL database (not a RDBMS i.e. not using SQL language).
 Mongo concepts can be mapped to RDBMS:
    - Database  ->  Database
    - Table     ->  Collection
    - Row       ->  Document
    - Columns   ->  Fields
    - Primary key -> _id field
* Mongo docs are stored in Binary JSON format (BSON).
* Mongo records are JSON data:
 MongoDb have flexible schema (unlike RDBMS).

Mongo Installation
* Download Mongo Community edition from official website and install.
* It installs
    * Mongo server -- mongod.exe (listens port 27017) -- runs in background (no ui).
    * Mongo clients
        -- Mongo Compass -- gui client (installed by default in modern mongo).
        -- Mongo Shell -- cli client (need to install separately in modern mongo).
            - Follows JS syntax.
*/

//____________________________________________________________________
// Mongo Commands
cmd > mongosh
// test> show databases

// Create a database :
//test > use classwork_db


// to chk current database :
// db

// create a person collection(table)
// insert one document(row) into person collection
// syntax : current_db.collection_name.insertOne({})


// current_database.collection.insertOne({doc1})
db.person.insertOne({
    name : "Nisha",
    email : "nisha@gmail.com",
    phone_no : 7057590799,
    age : 39
})


db.person.insertOne({
    name : "Disha",
    address :
    {
        area : "wakad",
        city : "pune",
        pin: 411057
    },
    hobbies : ['singing','sleeping']
})
/*
classwork_db> show databases;
admin         40.00 KiB
classwork_db  72.00 KiB
config        88.00 KiB
local         72.00 KiB
classwork_db> show collections
person
*/


// syntax to insert many documents at a time.
//current_database.collection_name.insertMany([{doc1},{doc2},{doc3}...])
db.person.insertMany([
    {
        name : "sunbeam",
        website : "www.sunbeaminfo.com",
        telephone : 1223443545
    },
    {
        _id : 1,
        name : "harsh",
        age : 23,
        degree : "B.E"
    }
])

// to chk the documents :
// syntax : current_db.coll_name.find()
db.person.find()
// displays all the documents :
// like : SELECT * FROM tbl;


//______________________________________________________________
// Commands to insert document in collection
// db.colname.insertOne({new json doc})
// db.colname.insertMany([ {new json doc1}, {new json doc2}, ... ])







//________________________________________________________
// Emp and dept collections :
db.dept.insertMany([
    {_id:10,dname:"ACCOUNTING",loc:"NEW YORK"},
    {_id:20,dname:"RESEARCH",loc:"DALLAS"},
    {_id:30,dname:"SALES",loc:"CHICAGO"},
    {_id:40,dname:"OPERATIONS",loc:"BOSTON"}
]);

db.emp.insertOne({_id:7369,ename:"SMITH",job:"CLERK",mgr:7902,sal:800.00,deptno:20});
db.emp.insertOne({_id:7499,ename:"ALLEN",job:"SALESMAN",mgr:7698,sal:1600.00,comm:300.00,deptno:30});
db.emp.insertOne({_id:7521,ename:"WARD",job:"SALESMAN",mgr:7698,sal:1250.00,comm:500.00,deptno:30});
db.emp.insertOne({_id:7566,ename:"JONES",job:"MANAGER",mgr:7839,sal:2975.00,deptno:20});
db.emp.insertOne({_id:7654,ename:"MARTIN",job:"SALESMAN",mgr:7698,sal:1250.00,comm:1400.00,deptno:30});
db.emp.insertOne({_id:7698,ename:"BLAKE",job:"MANAGER",mgr:7839,sal:2850.00,deptno:30});
db.emp.insertOne({_id:7782,ename:"CLARK",job:"MANAGER",mgr:7839,sal:2450.00,deptno:10});
db.emp.insertOne({_id:7788,ename:"SCOTT",job:"ANALYST",mgr:7566,sal:3000.00,deptno:20});
db.emp.insertOne({_id:7839,ename:"KING",job:"PRESIDENT",sal:5000.00,deptno:10});
db.emp.insertOne({_id:7844,ename:"TURNER",job:"SALESMAN",mgr:7698,sal:1500.00,comm:0.00,deptno:30});
db.emp.insertOne({_id:7876,ename:"ADAMS",job:"CLERK",mgr:7788,sal:1100.00,deptno:20});
db.emp.insertOne({_id:7900,ename:"JAMES",job:"CLERK",mgr:7698,sal:950.00,deptno:30});
db.emp.insertOne({_id:7902,ename:"FORD",job:"ANALYST",mgr:7566,sal:3000.00,deptno:20});
db.emp.insertOne({_id:7934,ename:"MILLER",job:"CLERK",mgr:7782,sal:1300.00,deptno:10});

//_________________________________________________________
/* _id is unique identity of each document (record).
    - If _id not given in insert operation, a new id is auto-generated by mongo client.
    - This auto-generated id is of 12 bytes and guranteed to be unique.
    - If _id given in insert operation, it will be used to uniquely identify the document. Duplicate _id is not allowed - will cause error.
*/

// db.colname.find(criteria, projection) -> mongo cursor
// db.colname.findOne(criteria, projection) 


/* Mongo cursor functions
    - sort() - returns cursor : DESC -> -1 , ASC -> 1
    - limit() - returns cursor
    - skip() - returns cursor
    - pretty() - default nowadays (void)
    - count() - returns integer
*/

// sort emps by sal in desc order
// SELECT * FROM emp ORDER BY sal DESC;

db.emp.find().sort({sal : -1})


//__________________________________________
// sort emps by deptno and job in asc order
// SELECT * FROM emp ORDER BY deptno ASC, job ASC
db.emp.find().sort({deptno : 1,job : 1})



//________________________________________________
// find emp with highest sal
// SELECT * FROM emp ORDER BY sal DESC LIMIT 1
db.emp.find().sort({sal : -1}).limit(1)


//_______________________________________________________
// find emp with third lowest sal
// SELECT * FROM emp ORDER BY sal ASC LIMIT 2, 1

db.emp.find().sort({sal : 1}).skip(2).limit(1)


// display the count of documents (rows)
db.emp.find().count()

//______________________________________________________
/*
 db.colname.find( {criteria}, { projection })
    * projection: colname: 1/0, colname: true/false
    * when no criteria { empty }: all records fetched
*/


// Projection
// Display the _id,ename and sal using inclusion((what to display))
db.emp.find({},{_id : 1, ename : 1, sal : 1})


// Projection using exclusion (what not to display)
// do not display job,hire,comm,mgr
db.emp.find({},{job:0, hire:0, comm:0, mgr: 0})


db.emp.find({},{_id : 1, ename : 0, sal : 1, comm: 0});
// ERROR: Cannot do exclusion on field sal in inclusion projection



// display on ename and job :
db.emp.find({},{ename: 1, job: 1})
// by default _id column is always displayed



// do not show _id, show ename & job
// inclusion projection should not contain exclusion fields. but _id is exception.
db.emp.find({},{_id:0, ename : 1, job : 1})
// allowed 



//____________________________________________________________
/* db.colname.find({criteria})
    - condition can be given
        - using comparison operators: $eq (default), $ne, $gt, $lt, $gte, $lte
        - using logical operators: $and, $or, $nor
        - using misc operators: $in, $nin, $exists, ...
*/

// SELECT * FROM emp WHERE ename='KING';
db.emp.find({ename : 'KING'})

db.emp.find({
    ename : {$eq : 'KING'}
})




// SELECT * FROM emp WHERE deptno=10;
db.emp.find({deptno : 10})


// SELECT * FROM emp WHERE sal > 2500;
db.emp.find({
    sal : {$gt : 2500}
})



// SELECT * FROM emp WHERE deptno != 30;
db.emp.find({
    deptno : {$ne : 30}
})


// SELECT * FROM emp WHERE job IN ('ANALYST', 'PRESIDENT', 'MANAGER');

db.emp.find({
    job : {$in : ['ANALYST','PRESIDENT','MANAGER']}
})



// SELECT * FROM emp WHERE deptno = 20 AND job = 'MANAGER';
db.emp.find({
    $and : [
        {deptno : 20},
        {job : 'MANAGER'}
    ]    
})


//__________________________________________________________
// SELECT * FROM emp WHERE deptno = 10 OR job = 'ANALYST';

db.emp.find({
    $or : [
        {deptno : 10},
        {job : 'ANALYST'}
    ]
})




//___________________________________________________________
// SELECT * FROM emp WHERE sal < 1000 OR sal > 3000;

db.emp.find({
    $or : [
        {sal : {$lt : 1000}},
        {sal : {$gt : 3000}}
    ]
})


//___________________________________________________
// SELECT * FROM emp WHERE ename = 'king';
db.emp.find({ename : 'king'})
db.emp.find({ename : /king/i})
// i stands for ignore the case


// to search with patterns use regex syntax /pattern/
// regex option "i" makes search case in-sensitive



// create regex patterns using wild-card chars
//  ^ -- match at the start
//  $ -- match at the end
//  [a-z] -- match any char in range a-z
//  {}, ., +, ?, ...

// Display the enames starting with M :
// SELECT * FROM emp WHERE ename LIKE 'M%'
db.emp.find({ename : /^M/})


//__________________________________________________
// Display the enames ending with ER :
// SELECT * FROM emp WHERE ename LIKE '%ER'
db.emp.find({ename : /ER$/})



//______________________________________________________
// Display the enames containing U :
// SELECT * FROM emp WHERE ename LIKE '%U%'
db.emp.find({ename : /U/})


//_____________________________________________________
// find emp whose name contains 4 alphabets
db.emp.find({ename : /^[A-Z][A-Z][A-Z][A-Z]$/})


//___________________________________________________
// find emps that have comm field.
db.emp.find({comm : {$exists : true}})




//_________________________________________________________________
// display name, job, sal, deptno of CLERK with 2nd highest sal.
// SELECT ename, job, sal, deptno FROM emp WHERE job = 'CLERK' ORDER BY sal DESC LIMIT 1, 1

db.emp.find({job : 'CLERK'}, {ename : 1, job : 1,sal : 1, deptno:1}).sort({sal : -1}).skip(1).limit(1)



// _______________________________________________________________
// db.colname.updateOne(criteria, changes, options)
// db.colname.updateMany(criteria, changes, options)
// changes: $set, $inc, $mul, ...

// increment age of person by 1.
db.person.updateOne({name : 'harsh'},
{$inc :{age : 1 }})


// decrement age of person by 1.
db.person.updateOne({name : /nisha/i},
    {$inc :{age : -1}})

// update the address of person.
db.person.updateOne({name : /disha/i},
    {$set : {
        area : 'hinjewadi',
        flatno : 'A123'
        }  
} 
)


// increase sal of all emps by 1000.
db.emp.updateMany({},
    {$inc :{sal : 1000}} 
    )



// upsert :
db.person.updateOne({_id : 2}, 
    {
        $set : {name : 'shubham',
                hobbies : ['shayari','coding']}
    },
    {upsert : true})




//_____________________________________________________________
/*
* db.colname.deleteOne({criteria})
* db.colname.deleteMany({criteria})
*/

// DELETE FROM person WHERE name = 'Nisha';
db.person.deleteOne({name : 'Nisha'})


// DELETE FROM person WHERE age > 20;
db.person.deleteOne({age : {$gt : 20}})

// DELETE FROM person;
db.person.deleteMany({})


// check the collection :
 db.person.find()


// drop the person collection :

db.person.drop()

// check the collection again:


//_______________________________________________________________
/*
#### Mongo Indexes
* Faster searching
* Types of indexes: Simple index, Composite index, Unique index, Geospatial index
* Syntax: db.colname.createIndex({field1: 1/-1, ...}, {options})
*/
//  Simple Index
// create an index on the deptno column    
// CREATE INDEX idx_deptno_emp ON emp(deptno);
db.emp.createIndex({deptno : 1})


// ____________________________________________________
// Composite Index
// create an index on deptno and job column together  
// CREATE INDEX idx_deptno_job ON emp(deptno,job);
db.emp.createIndex({deptno : 1, job : 1})

    // search by deptno & job will be faster
  
 //___________________________________________________
//Unique Index
// create a unique index on ename column
    // search by ename will be faster
    // duplicate ename not allowed

db.emp.createIndex({ename : 1},{unique : true})


// By default each mongo collection is indexed on "_id" field. 
// It is unique index.
// Index operations
   

//_______________________________________________________________
    // show list of indexes with getIndexes
db.emp.getIndexes()

    // drop index on deptno field    
db.emp.dropIndex(deptno)

//__________________________________________________________________
/*
 Mongo Aggregation Pipeline
Enables advanced mongo query features like grouping, joins, sorting, projection, filtering, ...
Syntax: db.colname.aggregate([
    { stage1 },
    { stage2 },
    { stage3 },
    ...
])
*/


/*
Display the deptno,max sal and total sal for all the emps deptwise.
include only emps with sal greater than 1000. 
sort the data in desc order of total sal.

SELECT deptno,MAX(sal),SUM(Sal) total_Sal 
FROM emp
WHERE sal > 1000
GROUP BY deptno
ORDER BY total_Sal DESC;
*/

db.emp.aggregate([
    {$match : {sal : {$gt : 1000}}},
    {$group :
    {
        _id : "$deptno",
        total_sal : {$sum : "$sal"},
        max_sal : {$max : "$sal"}
    }
},
    {$sort : {total_sal : 1}},
    {
    $project : 
        {
            _id : 0,
            deptno : "$_id",
            total_sal : 1,
            max_sal : 1
        }
    }
])

/*  
  

  The $match stage filters employees whose salary is greater than or equal to 1000. 
  The $group stage groups the remaining employees according to deptno and 
  calculates the total salary using $sum and maximum salary using $max. 
  The $sort stage sorts the departments in descending order of total salary using -1. 
  Finally, $project displays the department number, total salary, and maximum salary while 
  hiding the _id field.

Memory trick

M → G → S → P

Match → Group → Sort → Project

Think:

Filter → Calculate → Arrange → Display.
*/

//__________________________________________________________________________
//   Joining collections :
 // SELECT * FROM emp JOIN dept ON emp.deptno = dept.deptno;

//  $lookup is used to combine related documents from two MongoDB collections.

db.emp.aggregate([
   { $lookup :{
    from : "dept",
    localField : "deptno",
    foreignField : "_id",
    as : "dept_details"
    }
}
])

  /*
Four imp parts :

from  : name of the table/ collection to connect with emp
localField : name of the field in emp table : emp.deptno
foreignField : name od the field in another collection : dept._id
as : Store the matching department documents inside a new field called d.

Before $lookup :
{
    empno: 102,
    ename: "ALLEN",
    sal: 1600,
    deptno: 30
}

After $lookup :

{
    empno: 102,
    ename: "ALLEN",
    sal: 1600,
    deptno: 30,

    dept_details : [
        {
            _id: 30,
            dname: "SALES",
            loc: "CHICAGO"
        }
    ]
}

notice that d is an array :
$lookup returns the matching documents as an array.

Why?

Because one employee could potentially match:

zero documents
one document
multiple documents

So MongoDB uses an array.

In simple English:

For every employee in the emp collection, find the department document from the dept collection whose _id matches the employee's deptno, 
and store the matching department information in a new field called d.


| `$lookup` field | Meaning                            |
| --------------- | ---------------------------------- |
| `from`          | Collection to search               |
| `localField`    | Field in current collection        |
| `foreignField`  | Matching field in other collection |
| `as`            | Name of the new output field       |




Easy memory trick:

FROM → Where to search
LOCAL → My collection's field
FOREIGN → Other collection's field
AS → Where to put the result

*/

//____________________________________________________________________
// drop the classwork database 

db.dropDatabase("classwork_db")




